server:
  ssl:
    key-store: classpath:keystore1.p12
    key-store-password: password
    key-store-type: pkcs12
    key-alias: 1
    key-password: password
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chores1
    username: "rob"
    password: "mobius42"
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
    show-sql: true
  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
